### ISSUE TITLE
Missing file 'test/file.erb'

### ISSUE THREAD

**Issue by phiggins** [seattlerb/debride-erb#1]
Looks like you forgot to commit a file the tests depend on:

```
pete@balloon:~/projects/debride-erb$ rake
/home/pete/.rvm/rubies/ruby-2.2.0/bin/ruby -w -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/test_debride_erb.rb"' -- 
Run options: --seed 8021

# Running:

E

Finished in 0.000870s, 1149.1387 runs/s, 0.0000 assertions/s.

  1) Error:
TestDebride::TestErb#test_process_erb:
Errno::ENOENT: No such file or directory @ rb_sysopen - test/file.erb
    /home/pete/projects/debride-erb/lib/debride_erb.rb:17:in `read'
    /home/pete/projects/debride-erb/lib/debride_erb.rb:17:in `process_erb'
    /home/pete/projects/debride-erb/test/test_debride_erb.rb:8:in `test_process_erb'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [/home/pete/.rvm/rubies/ruby-2.2.0/bin/ruby...]
/home/pete/.rvm/gems/ruby-2.2.0@debride-erb/gems/hoe-3.13.1/lib/hoe/test.rb:83:in `block in define_test_tasks'
Tasks: TOP => default => test
(See full trace by running task with --trace)
pete@balloon:~/projects/debride-erb$ ls -l test/
total 4
-rw-rw-r-- 1 pete pete 402 Apr  4 13:14 test_debride_erb.rb
```

**Comment by zenspider** [comment]
Fixed! Sorry!
